sudo: required
dist: trusty

language: c

compiler:
  - clang
  - gcc

cache:
  directories:
    - $HOME/cmocka

env:
  - CFLAGS="-W -Wall -Wextra -Wpedantic -Wpointer-arith -Wstrict-prototypes -Wshadow -Werror"

script:
  - sed -i 's/BACKEND_\(.*\)=no/BACKEND_\1=yes/' config.mk # Enable all backends for test build
  - make V=yes
  - CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib" make check

notifications:
  email: false

addons:
  apt:
    packages:
      - libfreeimage-dev
      - libjpeg-turbo8-dev
      - libpng-dev
      - librsvg2-dev
      - libsdl2-ttf-dev

install:
  # Note: travis concatinates lines belonging to the same item
  - if [ ! -d $HOME/cmocka/cmocka-1.1.0 ];
    then
      curl "https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz" | tar xJf - -C $HOME/cmocka &&
      cd $HOME/cmocka &&
      env CFLAGS="-O2 -pipe" cmake cmocka-1.1.0 &&
      env CFLAGS="-02 -pipe" make &&
      cd -;
    fi
  - sudo make -C $HOME/cmocka install
  - sudo ldconfig
